##############################################################
# Requetes http pour le test de l'API
##############################################################
### Définition des variables globales

@hostname = http://localhost:8001
@id = 551454
####
#### Get list de contacts reçus 
#### 
GET {{hostname}}/contacts HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Get list de contacts reçus 
#### 
GET {{hostname}}/contacts/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Creer un nouveau contact
####
POST {{hostname}}/contacts HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    //"codeContact": "1", 
    "nom": "Antognolli", 
    "prenom": "Bruno", 
    "courriel": "bruno@gmail.com", 
    "telephone": "5813089368", 
    "messageContact": "Internet, Web, and mobile applications that provide security, but also anonymity of users, are gaining increasing interest and importance. Examples of such new applications are various innovative payment systems, digital notaries, electronic voting, sharing of sensitive documents, electronic auctions, medical applications, and many others. The common characteristic of these applications is that they all require anonymity of users and their transactions. In addition to their anonymity, user identifiers, data, and transactions handled by those applications also require standard security services, such as identification, authentication, and authorization of users, data confidentiality, data integrity, sender’s/receiver’s authenticity, and non-repudiation of transactions. Providing these security services in combination with anonymity is especially challenging, because all of them require explicit user identification and authentication.", 
    "dateReceptionMessage": "20210618", 
    "indicateurEtatMessage": "R", 
    "tokenReponse": "as138haljsbd293bqldb923qlwdb293dh3f24twvyj6ukjwq33==", 
    "codeMembre": null
}

#### ************************************************************************************************
####  Users 
#### ************************************************************************************************

####
#### GET /users - Lists all users
#### 
GET {{hostname}}/users HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### GET /users/:id - get a specific user 
#### 
GET {{hostname}}/users/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### POST /users - creates a new user
####
POST {{hostname}}/users HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "codeUser": "1", 
    "nom": "Torres dos Santos", 
    "prenom": "Julio Cesar", 
    "courriel": "juliozohar@gmail.com", 
    "codeMembre": "1", 
    "motPasse": "adasdedeerf#asdlkjasdkljasdklasdklasdlkad==", 
    "niveauPermission": "A"
}

####
#### PATCH /users/:id - update the data for a specific user 
#### 
PATCH {{hostname}}/users/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "codeUser": "1", 
    "nom": "Torres", 
    "prenom": "Julio ", 
    "courriel": "juliozohar@gmail.com", 
    "codeMembre": "1", 
    "motPasse": "GSDFSDFSDFDFKLJ#ASDDGLKJASDHFLKJAHFKJAHSDF==", 
    "niveauPermission": "B"
}

####
#### DELETE /users/:id - remove a specific user 
#### 
DELETE {{hostname}}/users/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json