# ###
# Filename: docker.mysql.dev
# Fichier docker de construction du containeur de la base de données 
# de l'application du Club de Judo de Québec.
#
# Author: Julio-Cesar Torres <juliozohar@gmail.com> (@juliozohar)
# Date: 2021-06-03
#
#   Copyright 2021 Kryptogarten LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ###
FROM mysql

ENV LANG=C.UTF-8

COPY CJQ-DDL.sql    /docker-entrypoint-initdb.d/1.sql
COPY CJQ-DML.sql    /docker-entrypoint-initdb.d/2.sql
COPY CJQ-config.sql /docker-entrypoint-initdb.d/3.sql

EXPOSE 3308
EXPOSE 8080
