##############################################################
# Requetes http pour le test de l'API
##############################################################
### Définition des variables globales

@hostname = http://localhost:8001
@codeUser = 1
####
#### Get list de users reçus 
#### 
GET {{hostname}}/users HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Get list de users reçus 
#### 
GET {{hostname}}/users/{{codeUser}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Creer un nouveau users
####
POST {{hostname}}/users HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "username": "MB84",
    "codeMembre": 1,
    "motPasse": "sdlkjsdsd2",
    "statusUser": "Z",
    "niveauPermission": "simple"
}

####
#### PATCH /users/:codeUser - update the data for a specific user 
#### 
PATCH {{hostname}}/users/{{codeUser}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "username": "torj01",
    "codeMembre": 1,
    "motPasse": "elfkhefoi8h3e89ejqeb79wet73rb4y0thm092",
    "statusUser": "A",
    "niveauPermission": "sysadm"
}

####
#### DELETE /users/:codeUser - remove a specific user 
#### 
DELETE {{hostname}}/users/{{codeUser}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json


