##############################################################
# Requetes http pour le test de l'API
##############################################################
### Définition des variables globales

@hostname = http://localhost:8001
@id = 1
####
#### Get list de customers reçus 
#### 
GET {{hostname}}/customers HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Get list de customers reçus 
#### 
GET {{hostname}}/customers/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Creer un nouveau customer
####
POST {{hostname}}/customers HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "name": "Zemane", 
    "email": "zema@gmail.com", 
    "active": true
}
####
#### PATCH /users/:id - update the data for a specific customer 
#### 
PUT {{hostname}}/customers/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "name": "Julio Cesar Torres dos Santos", 
    "email": "juliozohar@gmail.com", 
    "active": true
}

####
#### DELETE /users/:id - remove a specific customer 
#### 
DELETE {{hostname}}/customers/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json


#### 
#### ###########################################################################
#### 
@codeContact = 1
####
#### Get list de customers reçus 
#### 
GET {{hostname}}/contacts HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Get list de customers reçus 
#### 
GET {{hostname}}/contacts/{{id}} HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

####
#### Creer un nouveau customer
####
POST {{hostname}}/contacts HTTP/1.1
X-API-Key: no-key-at-all
Content-Type: application/json

{
    "nom": "Torres dos Santos",
    "prenom" : "Edjara",
    "courriel": "edjara@gmail.com",
    "telephone": "5813077882",
    "messageContact": "Teste de l'API de la banque avec accentuéés et joão",
    "indicateurEtatMessage": "R",
    "tokenReponse": "ewihasdlkh238ysfdlkhfo84y89y13",
    "codeMembre": null
}