# ###
# Filename: Dockerfile.frontend.dev
# Fichier docker de construction du containeur du frontend de l'application
# du Club de Judo de Québec.
# Author: Julio-Cesar Torres <juliozohar@gmail.com> (@juliozohar)
# Date: 2021-06-03
#
#   Copyright 2021 Kryptogarten LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ###

FROM node:14.15.0-alpine3.12 as builder

# Create a directory where our app will be placed
RUN mkdir -p /app

# Change directory so that our commands run inside this new directory
WORKDIR /app

# Copy dependency definitions 
COPY package*.json /app/

# Install dependencies 
RUN npm install 

# Set the path to node_modules 
ENV PATH /app/node_modules/.bin:$PATH

# Get all the code needed to run the app 
COPY . /app/ 

# Expose the port the app runs in
EXPOSE 4200
